package radio

const (
	// The version of the wraith_module_comosum protocol supported by the current
	// version of the module. This is updated whenever a breaking change is made to
	// the protocol.
	// Typically generated by hashing a string describing the protocol. Unofficial
	// versions must be namespaced, by means of a prefix before the hash!
	// 0: md5("let there be light")
	CURRENT_PROTO = "bd52000e8ba92c956413c49794d3a600"

	// The range of ports the Comosum client can bind to on the Yggdrasil interface.
	// This is randomized to make detection more difficult from within the Yggdrasil
	// network by port scans for instance.
	MGMT_LISTEN_PORT_MIN = 10000
	MGMT_LISTEN_PORT_MAX = 50000

	// The port on the C2 which Comosum clients connect to.
	C2_PORT = 45235

	// The prefix for all Comosum HTTP routes.
	ROUTE_PREFIX = "/_comosum/" + CURRENT_PROTO + "/"
)
